server:
  port: 8011

spring:
  application:
    name: VR-USER-SERVICE
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      defer-datasource-initialization: true
      show-sql: true
